install.packages(httr)
install.packages(shiny)
install.packages(dplyr)
install.packages(ggplot2)
install.packages(ggrepel)
install.packages(shinythemes)
install.packages(ggthemes)
install.packages(RColorBrewer)
